<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<style type="text/css">
<!--
.style1 {font-size: 36px;
	font-weight: bold;
}
.style5 {font-size: 18px}
.style7 {font-size: 18px; color: #00FFFF; }
-->
body {

	background-image:url(images/Rainbow-Background-Images-173.jpg);
	background-repeat:repeat-y;
	
}
</style>
</head>

<body>
<?php
include "include.php";
?>
<table width="1111" height="469" border="0">
  <tr>
    <td width="107" height="139">&nbsp;</td>
    <td width="858"><p align="center" class="style1">Car Maintenance and Servicing Tips</p>
    <p align="left" class="style1"><span class="style5"><a href="maintanance.php">Back</a></span></p></td>
    <td width="124">&nbsp;</td>
  </tr>
  <tr>
    <td height="249">&nbsp;</td>
    <td><h1><strong>Which Car Servicing Shop Is Good For Your Car?</strong></h1>
      <p><strong>How To Find A Good Car Servicing Shop?</strong></p>
      <p>Car servicing is important for maintaining the overall health of your vehicle however you can’t pick up a local workshop for servicing. Buying a car is a huge investment and you can’t allow unskilled people to do car servicing for your car hence finding a reputed car servicing/ repair centre becomes all important. There are many good vehicle repair centers in India that claims to refurbish your vehicle however most of them aren’t recognized. Most car owners end up going to an authorized servicing centre, which may charge extremely high while others end up going to local workshop that completely ruins the efficiency of your car. It’s become difficult for the car owner to actually find an affordable branded shop.</p>
      <p><img src="servicing.jpg" width="560" height="373" /><br />
               </p>
      <p><strong>Top Tips to Find a Good Car Servicing Centre in India</strong></p>
      <p><strong>Reputed Car Repair Service: </strong>Car owners should visit servicing centers, which are reputed. Reputation mainly comes from media mentions, the person behind the organization, track record and word of mouth. Always search for a workshop with skilled man power and good customer relationship backup.</p>
      <p><strong>Online Reputation: </strong>Car owners mainly search for good centers on the web. It’s always advisable to read reviews, check their social media presence and visit website before taking an appointment. Most good car servicing centers are very transparent.</p>
      <p><strong>Quality: </strong>Quality is the key hence one should search for shops that give world class treatment in an affordable price.</p>
      <p><strong>Comfort: </strong>Waiting for your car can be a daunting task for many hence it’s important to look into the comfort factor provided by the centre too. There are good car servicing centers across India that provides an air conditioned waiting room with TV, newspaper and magazines.</p>
    <p><strong>Professionalism: </strong>It’s important to repair your car in a professional environment. Always opt for service centers that have well mannered staff.</p>
    <p><strong><span class="style7">To get the best deals on car servicing</span>, <a href="excistservice.php">click here</a></strong>.</p></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
</body>
</html>
